#Basic python3 runtime
runtime: python38
runtime_config:
  python_version: 3

#Application
.gcloudignore
.gitignore

env: standard
default_expiration: "7d"

#Handlers
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
